### ISSUE TITLE
desktop ui qa checklist

### ISSUE THREAD

**Issue by brandonnorsworthy** [brandonnorsworthy/eridium#19]
- [x] all server icons can handle any image
- [x] can handle any length of server names
- [x] channel names can handle any length
- [x] can handle any user profile pictures
- [x] any username for person logged in
- [x] channel name does not scrunch down if too small
- [x] channel description does not wrap will try to overflow and cut off with ...
- [x] username in messages does not word wrap
- [x] time stuff does not word wrap
- [x] user images cannot be bigger than the viewport
