### ISSUE TITLE
random todo list

### ISSUE THREAD

**Issue by brandonnorsworthy** [brandonnorsworthy/eridium#23]
- [x] #25
- [ ] day line seperators look at figma to understand
- [x] #20
- [ ] #137
- [x] #27
- [x] #28
- [x] #47
- [x] #30
- [ ] you can right click any channel and edit or delete the channel
- [ ] editing a channel you can change the name or change the topic (topic is empty by default)
- [ ] #138
- [ ] clicking a message authors username (profile modal)
- [ ] javascript to test if @person person is in the server to make it colored
- [x] #132
- [x] #133
- [x] #134
